ALTER TABLE `audit_logs`
  MODIFY `action` ENUM(
    'LOGIN',
    'LOGOUT',
    'AUTH_FAILURE',
    'TENANT_REGISTERED',
    'PASSWORD_RESET_REQUESTED',
    'PASSWORD_RESET_COMPLETED',
    'OAUTH_LINKED',
    'OAUTH_UNLINKED',
    'MFA_CHANGED',
    'USER_INVITED',
    'USER_CREATED',
    'USER_UPDATED',
    'ROLE_CHANGED',
    'SESSION_REVOKED',
    'ONBOARDING_UPDATED',
    'CUSTOMER_CHANGED',
    'CARRIER_CHANGED',
    'FREIGHT_PRICING_CHANGED',
    'FREIGHT_SIMULATION_CREATED',
    'FREIGHT_OPTION_SELECTED',
    'SHIPMENT_CREATED',
    'IMPORT_CREATED',
    'IMPORT_STARTED',
    'IMPORT_COMPLETED',
    'IMPORT_FAILED',
    'IMPORT_CANCELED',
    'IMPORT_RETRIED',
    'IMPORT_FILE_DOWNLOADED',
    'INSIGHT_GENERATED',
    'INSIGHT_READ',
    'INSIGHT_DISMISSED',
    'ADMIN_OPERATION'
  ) NOT NULL;

CREATE TABLE `insights` (
  `id` CHAR(36) NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `dedupe_key` VARCHAR(180) NOT NULL,
  `type` VARCHAR(80) NOT NULL,
  `category` ENUM('COST', 'DEADLINE', 'CARRIER', 'ROUTE', 'CUSTOMER', 'OPERATION', 'IMPORT', 'DATA_QUALITY') NOT NULL,
  `severity` ENUM('INFO', 'OPPORTUNITY', 'WARNING', 'CRITICAL') NOT NULL,
  `title` VARCHAR(180) NOT NULL,
  `description` VARCHAR(700) NOT NULL,
  `evidence` JSON NOT NULL,
  `metric_value` DECIMAL(14, 4) NULL,
  `comparison_value` DECIMAL(14, 4) NULL,
  `percentage_change` DECIMAL(9, 4) NULL,
  `period_start` DATETIME(3) NOT NULL,
  `period_end` DATETIME(3) NOT NULL,
  `resource_type` VARCHAR(80) NULL,
  `resource_id` CHAR(36) NULL,
  `action_url` VARCHAR(255) NULL,
  `status` ENUM('NEW', 'READ', 'DISMISSED', 'RESOLVED') NOT NULL DEFAULT 'NEW',
  `generated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `read_at` DATETIME(3) NULL,
  `dismissed_at` DATETIME(3) NULL,
  `metadata` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `insights_tenant_dedupe_key_key` (`tenant_id`, `dedupe_key`),
  INDEX `insights_tenant_status_generated_idx` (`tenant_id`, `status`, `generated_at`),
  INDEX `insights_tenant_category_severity_idx` (`tenant_id`, `category`, `severity`, `generated_at`),
  INDEX `insights_tenant_period_idx` (`tenant_id`, `period_start`, `period_end`),
  CONSTRAINT `insights_tenant_id_fkey` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
