'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Building2, CheckCircle2, Plus, RefreshCw, Save, Truck } from 'lucide-react';
import { useState, type ComponentType, type FormEvent, type ReactNode } from 'react';
import NextLink from 'next/link';

import styles from './logistics-management.module.css';
import { EmptyState } from '@/components/feedback/empty-state';
import { ApiClientError } from '@/services/http-client';
import { getBranches, getCarriers, logisticsAdminQueryKeys, saveBranch, saveCarrier, saveCarrierService, toggleBranch, toggleCarrier, type BranchInput, type CarrierInput, type ServiceInput } from '@/services/logistics-admin-service';
import { cleanCode, cleanDigits, cleanOptionalText, cleanState, cleanText, isValidEmail, isValidUrl, parseLocaleNumber } from './form-normalizers';

const Link = NextLink as unknown as ComponentType<{ href: string; children?: ReactNode; [key: string]: unknown }>;

type Tab = 'branches' | 'carriers';
const emptyBranch: BranchInput = { name: '', code: '', postalCode: '', street: '', number: '', district: '', city: '', state: '', main: false };
const emptyCarrier: CarrierInput = { name: '', code: '', document: '', legalName: '', email: '', phone: '', contactName: '', site: '', notes: '' };
const emptyService: ServiceInput = { code: '', name: '', modality: 'rodoviario-economico', description: '', defaultDeadlineDays: 3, cubicFactor: 300, minWeightKg: 0, maxWeightKg: 1000, minimumValue: 0, status: 'ACTIVE' };
const serviceModalities = [
  { label: 'Rodoviário Econômico', value: 'rodoviario-economico' },
  { label: 'Rodoviário Expresso', value: 'rodoviario-expresso' },
  { label: 'Aéreo', value: 'aereo' },
  { label: 'Same Day', value: 'same-day' },
  { label: 'Carga Fracionada', value: 'fracionado' },
  { label: 'Carga Fechada', value: 'carga-fechada' },
];

export function LogisticsManagement({ initialTab = 'branches' }: { initialTab?: Tab }) {
  const client = useQueryClient();
  const [tab, setTab] = useState<Tab>(initialTab);
  const [branch, setBranch] = useState<BranchInput>(emptyBranch);
  const [carrier, setCarrier] = useState<CarrierInput>(emptyCarrier);
  const [service, setService] = useState<ServiceInput>(emptyService);
  const [selectedCarrier, setSelectedCarrier] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const branches = useQuery({ queryKey: logisticsAdminQueryKeys.branches, queryFn: () => getBranches(), retry: false });
  const carriers = useQuery({ queryKey: logisticsAdminQueryKeys.carriers, queryFn: () => getCarriers(), retry: false });
  const branchMutation = useMutation({ mutationFn: () => saveBranch(normalizeBranch(branch)), onSuccess: async () => { setBranch(emptyBranch); setMessage('Filial cadastrada.'); await client.invalidateQueries({ queryKey: logisticsAdminQueryKeys.branches }); } });
  const carrierMutation = useMutation({ mutationFn: () => saveCarrier(normalizeCarrier(carrier)), onSuccess: async () => { setCarrier(emptyCarrier); setMessage('Transportadora cadastrada.'); await client.invalidateQueries({ queryKey: logisticsAdminQueryKeys.carriers }); } });
  const serviceMutation = useMutation({ mutationFn: () => saveCarrierService(selectedCarrier as string, normalizeService(service)), onSuccess: async () => { setService(emptyService); setSelectedCarrier(null); setMessage('Serviço cadastrado.'); await client.invalidateQueries({ queryKey: logisticsAdminQueryKeys.carriers }); } });
  const statusMutation = useMutation<unknown, Error, { id: string; active: boolean; kind: Tab }>({ mutationFn: ({ id, active, kind }) => kind === 'branches' ? toggleBranch(id, active) : toggleCarrier(id, active), onSuccess: async () => { setMessage('Status atualizado.'); await Promise.all([client.invalidateQueries({ queryKey: logisticsAdminQueryKeys.branches }), client.invalidateQueries({ queryKey: logisticsAdminQueryKeys.carriers })]); } });

  function submit(event: FormEvent<HTMLFormElement>, kind: Tab): void { event.preventDefault(); setError(null); setMessage(null); const validation = kind === 'branches' ? validateBranch(branch) : validateCarrier(carrier); if (validation) { setError(validation); return; } if (kind === 'branches') branchMutation.mutate(); else carrierMutation.mutate(); }
  function submitService(event: FormEvent<HTMLFormElement>): void { event.preventDefault(); setError(null); setMessage(null); const validation = validateService(service); if (validation) { setError(validation); return; } serviceMutation.mutate(); }
  const activeError = error ?? messageFor(branchMutation.error ?? carrierMutation.error ?? serviceMutation.error ?? statusMutation.error);
  return <div className={styles.layout}>
    <div className={styles.tabs} role="tablist" aria-label="Cadastros logísticos">
      <button className={`${styles.tab} ${tab === 'branches' ? styles.activeTab : ''}`} role="tab" aria-selected={tab === 'branches'} onClick={() => setTab('branches')} type="button"><Building2 size={16} /> Filiais</button>
      <button className={`${styles.tab} ${tab === 'carriers' ? styles.activeTab : ''}`} role="tab" aria-selected={tab === 'carriers'} onClick={() => setTab('carriers')} type="button"><Truck size={16} /> Transportadoras e serviços</button>
    </div>
    {activeError ? <p className={styles.error} role="alert">{activeError}</p> : null}
    {message ? <p className={styles.success} role="status"><CheckCircle2 size={16} /> {message}</p> : null}
    {tab === 'branches' ? <section className={styles.panel} aria-labelledby="branches-title">
      <div className={styles.header}><div><h2 id="branches-title">Filiais</h2><p>Origens operacionais isoladas por empresa.</p></div><div className={styles.toolbar}><Link href="/branches/new">Nova filial</Link><button type="button" onClick={() => void branches.refetch()}><RefreshCw size={15} /> Atualizar</button></div></div>
      <form className={styles.form} onSubmit={(event) => submit(event, 'branches')}>
        <label>Nome<input required value={branch.name} onChange={(e) => setBranch({ ...branch, name: e.target.value })} /></label><label>Código<input required value={branch.code} onChange={(e) => setBranch({ ...branch, code: cleanCode(e.target.value) })} /></label><label>CEP<input value={branch.postalCode} onChange={(e) => setBranch({ ...branch, postalCode: cleanDigits(e.target.value) })} /></label><label className={styles.wide}>Logradouro<input value={branch.street} onChange={(e) => setBranch({ ...branch, street: e.target.value })} /></label><label>Número<input value={branch.number} onChange={(e) => setBranch({ ...branch, number: e.target.value })} /></label><label>Bairro<input value={branch.district} onChange={(e) => setBranch({ ...branch, district: e.target.value })} /></label><label>Cidade<input value={branch.city} onChange={(e) => setBranch({ ...branch, city: e.target.value })} /></label><label>Estado<input maxLength={2} value={branch.state} onChange={(e) => setBranch({ ...branch, state: cleanState(e.target.value) })} /></label><label><span> </span><span><input type="checkbox" checked={branch.main} onChange={(e) => setBranch({ ...branch, main: e.target.checked })} /> Filial principal</span></label><button type="submit" disabled={branchMutation.isPending}><Plus size={15} /> {branchMutation.isPending ? 'Salvando' : 'Cadastrar filial'}</button>
      </form>
      {branches.isPending ? <p className={styles.muted}>Carregando filiais...</p> : branches.data?.data.length === 0 ? <EmptyState title="Nenhuma filial cadastrada" description="Cadastre a primeira origem operacional." /> : <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Nome</th><th>Código</th><th>Localização</th><th>Status</th><th>Ações</th></tr></thead><tbody>{branches.data?.data.map((item) => <tr key={item.id}><td><Link href={`/branches/${item.id}`}>{item.name}</Link>{item.main ? ' (principal)' : ''}</td><td>{item.code}</td><td>{item.city ?? '-'} / {item.state ?? '-'}</td><td className={item.active ? styles.statusActive : styles.statusInactive}>{item.active ? 'Ativa' : 'Inativa'}</td><td><Link href={`/branches/${item.id}/edit`}>Editar</Link> <button type="button" onClick={() => statusMutation.mutate({ id: item.id, active: !item.active, kind: 'branches' })}>{item.active ? 'Desativar' : 'Ativar'}</button></td></tr>)}</tbody></table></div>}
    </section> : <section className={styles.panel} aria-labelledby="carriers-title">
      <div className={styles.header}><div><h2 id="carriers-title">Transportadoras</h2><p>Parceiros, serviços e status usados pela simulação.</p></div><div className={styles.toolbar}><Link href="/carriers/new">Nova transportadora</Link><button type="button" onClick={() => void carriers.refetch()}><RefreshCw size={15} /> Atualizar</button></div></div>
      <form className={styles.form} onSubmit={(event) => submit(event, 'carriers')}><label>Nome<input required value={carrier.name} onChange={(e) => setCarrier({ ...carrier, name: e.target.value })} /></label><label>Código<input value={carrier.code} onChange={(e) => setCarrier({ ...carrier, code: cleanCode(e.target.value) })} /></label><label>CNPJ<input value={carrier.document} onChange={(e) => setCarrier({ ...carrier, document: cleanDigits(e.target.value) })} /></label><label>Razão social<input value={carrier.legalName} onChange={(e) => setCarrier({ ...carrier, legalName: e.target.value })} /></label><label>E-mail<input type="email" value={carrier.email} onChange={(e) => setCarrier({ ...carrier, email: e.target.value.toLowerCase() })} /></label><label>Telefone<input value={carrier.phone} onChange={(e) => setCarrier({ ...carrier, phone: cleanDigits(e.target.value) })} /></label><label>Contato<input value={carrier.contactName} onChange={(e) => setCarrier({ ...carrier, contactName: e.target.value })} /></label><label>Site<input value={carrier.site} onChange={(e) => setCarrier({ ...carrier, site: e.target.value })} /></label><label className={styles.wide}>Observações<textarea value={carrier.notes} onChange={(e) => setCarrier({ ...carrier, notes: e.target.value })} /></label><button type="submit" disabled={carrierMutation.isPending}><Plus size={15} /> Cadastrar transportadora</button></form>
      {carriers.isPending ? <p className={styles.muted}>Carregando transportadoras...</p> : carriers.data?.data.length === 0 ? <EmptyState title="Nenhuma transportadora cadastrada" description="Cadastre um parceiro para ofertar serviços." /> : <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Transportadora</th><th>Documento</th><th>Serviços</th><th>Status</th><th>Ações</th></tr></thead><tbody>{carriers.data?.data.map((item) => <tr key={item.id}><td><Link href={`/carriers/${item.id}`}>{item.name}</Link><br /><span className={styles.muted}>{item.code ?? 'Sem código'}</span></td><td>{item.document ?? '-'}</td><td><div className={styles.serviceList}>{item.services?.map((s) => <span className={styles.service} key={s.id}>{s.name} <small>{s.status === 'ACTIVE' ? 'Ativo' : 'Inativo'}</small></span>)}<button type="button" onClick={() => setSelectedCarrier(item.id)}>Adicionar serviço</button>{selectedCarrier === item.id ? <form className={styles.form} onSubmit={submitService}><label>Código<input required value={service.code} onChange={(e) => setService({ ...service, code: cleanCode(e.target.value) })} /></label><label>Nome<input required value={service.name} onChange={(e) => setService({ ...service, name: e.target.value })} /></label><label>Modalidade<select required value={service.modality} onChange={(e) => setService({ ...service, modality: e.target.value })}>{serviceModalities.map((modality) => <option key={modality.value} value={modality.value}>{modality.label}</option>)}</select></label><label>Prazo (dias)<input inputMode="numeric" value={service.defaultDeadlineDays} onChange={(e) => setService({ ...service, defaultDeadlineDays: Math.trunc(parseLocaleNumber(e.target.value)) })} /></label><label>Fator cubagem<input inputMode="decimal" value={String(service.cubicFactor).replace('.', ',')} onChange={(e) => setService({ ...service, cubicFactor: parseLocaleNumber(e.target.value) })} /></label><label>Valor mínimo<input inputMode="decimal" value={String(service.minimumValue).replace('.', ',')} onChange={(e) => setService({ ...service, minimumValue: parseLocaleNumber(e.target.value) })} /></label><button type="submit" disabled={serviceMutation.isPending}><Save size={15} /> Salvar serviço</button></form> : null}</div></td><td className={item.active ? styles.statusActive : styles.statusInactive}>{item.active ? 'Ativa' : 'Inativa'}</td><td><Link href={`/carriers/${item.id}/edit`}>Editar</Link> <button type="button" onClick={() => statusMutation.mutate({ id: item.id, active: !item.active, kind: 'carriers' })}>{item.active ? 'Desativar' : 'Ativar'}</button></td></tr>)}</tbody></table></div>}
    </section>}
  </div>;
}

function messageFor(error: unknown): string | null { return error instanceof ApiClientError ? error.response.message : error ? 'Não foi possível concluir a operação.' : null; }
function normalizeBranch(input: BranchInput): BranchInput { return { ...input, city: cleanOptionalText(input.city), code: cleanCode(input.code), country: cleanOptionalText(input.country ?? 'BR'), district: cleanOptionalText(input.district), name: cleanText(input.name), number: cleanOptionalText(input.number), postalCode: cleanOptionalText(cleanDigits(input.postalCode)), state: cleanOptionalText(cleanState(input.state ?? '')), street: cleanOptionalText(input.street) }; }
function normalizeCarrier(input: CarrierInput): CarrierInput { return { code: cleanOptionalText(cleanCode(input.code ?? '')), contactName: cleanOptionalText(input.contactName), document: cleanOptionalText(cleanDigits(input.document)), email: cleanOptionalText(input.email?.toLowerCase()), legalName: cleanOptionalText(input.legalName), name: cleanText(input.name), notes: cleanOptionalText(input.notes), phone: cleanOptionalText(cleanDigits(input.phone)), site: cleanOptionalText(input.site) }; }
function normalizeService(input: ServiceInput): ServiceInput { return { code: cleanCode(input.code), cubicFactor: parseLocaleNumber(input.cubicFactor), defaultDeadlineDays: Math.trunc(parseLocaleNumber(input.defaultDeadlineDays)), description: cleanOptionalText(input.description), maxWeightKg: parseLocaleNumber(input.maxWeightKg), minWeightKg: parseLocaleNumber(input.minWeightKg), minimumValue: parseLocaleNumber(input.minimumValue), modality: cleanText(input.modality), name: cleanText(input.name), status: input.status ?? 'ACTIVE' }; }
function validateBranch(input: BranchInput): string | null { if (cleanText(input.name).length < 2) return 'Informe o nome da filial.'; if (cleanCode(input.code).length < 2) return 'Informe um código válido para a filial.'; if (input.postalCode && cleanDigits(input.postalCode).length !== 8) return 'Informe um CEP com 8 dígitos.'; if (input.state && cleanState(input.state).length !== 2) return 'Informe a UF com 2 letras.'; return null; }
function validateCarrier(input: CarrierInput): string | null { if (cleanText(input.name).length < 2) return 'Informe o nome da transportadora.'; if (input.document && cleanDigits(input.document).length !== 14) return 'Informe um CNPJ com 14 dígitos.'; if (!isValidEmail(input.email)) return 'Informe um e-mail válido.'; if (!isValidUrl(input.site)) return 'Informe uma URL válida.'; return null; }
function validateService(input: ServiceInput): string | null { const service = normalizeService(input); if (service.code.length < 2) return 'Informe um código válido para o serviço.'; if (service.name.length < 2) return 'Informe o nome do serviço.'; if (service.defaultDeadlineDays < 1) return 'O prazo deve ser maior que zero.'; if (service.cubicFactor < 1) return 'O fator de cubagem deve ser maior que zero.'; if ((service.maxWeightKg ?? 0) > 0 && (service.maxWeightKg ?? 0) <= (service.minWeightKg ?? 0)) return 'O peso máximo deve ser maior que o peso mínimo.'; return null; }
