ALTER TABLE `users`
  MODIFY `tenant_id` CHAR(36) NULL,
  MODIFY `status` ENUM('INCOMPLETE','PENDING','ACTIVE','BLOCKED','INVITED','DISABLED','DELETED') NOT NULL DEFAULT 'INVITED';

ALTER TABLE `oauth_accounts`
  MODIFY `tenant_id` CHAR(36) NULL;
