import { apiRequest } from './http-client';

export interface AdminPage<T> { data: T[]; meta: { page: number; perPage: number; total: number; totalPages: number } }
export interface AdminShipment { id: string; trackingCode: string; externalReference: string | null; carrierName: string; carrierServiceName: string; status: string; freightValue: number; estimatedDeliveryAt: string; createdAt: string }
export interface AdminRateTable { id: string; carrierName: string; serviceName: string; name: string; version: number; currency: string; validFrom: string; validTo: string | null; status: string; ranges: Array<{ minWeightKg: number; maxWeightKg: number; basePrice: number; pricePerKg: number; deadlineDays: number }>; charges: Array<{ name: string; type: string; fixedAmount: number | null; percentage: number | null }> }
export interface AdminAudit { id: string; action: string; entityType: string | null; entityId: string | null; actor: string; actorEmail: string | null; requestId: string | null; createdAt: string; metadata: unknown }
export interface AdminCoverage { id: string; carrierServiceId: string; carrierName: string; serviceName: string; status: string; originState: string | null; destinationState: string | null; originPostalCodeStart: string | null; originPostalCodeEnd: string | null; destinationPostalCodeStart: string | null; destinationPostalCodeEnd: string | null }
export interface ShipmentDetail { id: string; trackingCode: string; externalReference: string | null; status: string; freightValue: number; cargoValue: number | null; realWeightKg: number; chargeableWeightKg: number; estimatedDeliveryAt: string; deliveredAt: string | null; createdAt: string; carrier: { id: string; name: string } | null; service: { id: string; name: string } | null; customer: { id: string; name: string } | null; branch: { id: string; name: string } | null; addresses: Array<{ type: string; postalCode: string; street: string; number: string | null; city: string; state: string }>; packages: Array<{ quantity: number; weightKg: number; lengthCm: number; widthCm: number; heightCm: number; volumeM3: number; description: string | null }>; tracking: Array<{ id: string; eventType: string; status: string | null; description: string | null; occurredAt: string; receivedAt: string; location: string | null; externalCode: string | null; source: string }> }

export function getAdminShipments(): Promise<AdminPage<AdminShipment>> { return apiRequest<AdminPage<AdminShipment>>('/shipments?perPage=50'); }
export function updateShipmentStatus(id: string, status: string): Promise<AdminShipment> { return apiRequest<AdminShipment>(`/shipments/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }); }
export function getShipment(id: string): Promise<ShipmentDetail> { return apiRequest<ShipmentDetail>(`/shipments/${id}`); }
export function createTrackingEvent(id: string, input: { eventType: string; status?: string; description?: string; occurredAt: string; location?: string; externalCode?: string; idempotencyKey?: string }): Promise<unknown> { return apiRequest<unknown>(`/shipments/${id}/tracking-events`, { method: 'POST', body: JSON.stringify(input) }); }
export function getRateTables(): Promise<AdminPage<AdminRateTable>> { return apiRequest<AdminPage<AdminRateTable>>('/freight-rate-tables?perPage=50'); }
export function getRateTable(id: string): Promise<AdminRateTable & { tenantId?: string; notes?: string | null; coverages?: unknown[]; usedInSimulations?: number; previousVersion?: unknown; versions?: unknown[] }> { return apiRequest(`/freight-rate-tables/${id}`); }
export function saveRateTable(input: unknown, id?: string): Promise<unknown> { return apiRequest(id ? `/freight-rate-tables/${id}` : '/freight-rate-tables', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(input) }); }
export function createRateTableVersion(id: string): Promise<unknown> { return apiRequest(`/freight-rate-tables/${id}/new-version`, { method: 'POST' }); }
export function toggleRateTable(id: string, status: 'ACTIVE' | 'INACTIVE'): Promise<unknown> { return apiRequest(`/freight-rate-tables/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }); }
export function getAuditLogs(): Promise<AdminPage<AdminAudit>> { return apiRequest<AdminPage<AdminAudit>>('/audit-logs?perPage=50'); }
export function getCoverages(): Promise<AdminPage<AdminCoverage>> { return apiRequest<AdminPage<AdminCoverage>>('/coverages?perPage=50'); }
export function createCoverage(input: Record<string, string>): Promise<AdminCoverage> { return apiRequest<AdminCoverage>('/coverages', { method: 'POST', body: JSON.stringify(input) }); }
export function testCoverage(input: { originPostalCode: string; destinationPostalCode: string; carrierServiceId?: string }): Promise<{ covered: boolean; matches: Array<{ carrierName: string; serviceName: string; ruleId: string }> }> { return apiRequest<{ covered: boolean; matches: Array<{ carrierName: string; serviceName: string; ruleId: string }> }>('/coverages/test', { method: 'POST', body: JSON.stringify(input) }); }
